var imports = [
  "/starblast/mapeditor/index.html",
	"/starblast/mapeditor/icon_dark.png",
  "/starblast/mapeditor/icon_light.png",
  "/starblast/mapeditor/Asteroid.png",
	"/starblast/mapeditor/style.css",
	"/starblast/mapeditor/mapeditor.json",
	"/serviceWorker.js",
	"https://cdn.jsdelivr.net/gh/jquery/jquery/dist/jquery.min.js",
	"https://cdn.jsdelivr.net/gh/marcj/css-element-queries/src/ResizeSensor.min.js",
	"https://cdn.jsdelivr.net/gh/pieroxy/lz-string/libs/lz-string.min.js",
	"https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/ace.js",
	"https://kit.fontawesome.com/ccd821e6cb.js",
	"https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/mode-javascript.js",
	"https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/theme-monokai.js",
	"https://cdn.jsdelivr.net/gh/tombigel/detect-zoom/detect-zoom.min.js",
	"/starblast/mapeditor/script.js",
	"/starblast/mapeditor/presets.js"
];
